version: "3.8"

services:
  backend:
    build:
      context: ./BackEnd/Ssafy_Project
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ssafy_project?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ssafy
      SPRING_DATASOURCE_PASSWORD: ssafy
      CORS_ALLOWED_ORIGIN: http://localhost:5173
    networks:
      - project-network

networks:
  project-network:
    external: true